### ISSUE TITLE
Choosing an approach to transfer the dataframe from python to R

### ISSUE THREAD

**Issue by Anahita97** [UBC-MDS/Daily_Rainfall_Over_NSW_Group4#6]
The options are:
- [Parquet file](http://parquet.apache.org/)
- [Feather file](https://arrow.apache.org/docs/python/feather.html)
- [Pandas exchange](https://rpy2.github.io/doc/latest/html/interactive.html)
- [Arrow exchange](https://github.com/rpy2/rpy2-arrow)

**Comment by stevenlio88** [comment]
After a discussion with the team and comparing the results, we decided to go for Parquet method.
